# Generated by Django 4.2.5 on 2023-09-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=20)),
                ('talle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('talle', models.IntegerField()),
                ('estilo', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Indumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=20)),
                ('talle', models.IntegerField()),
            ],
        ),
    ]
