# Generated by Django 4.2.5 on 2023-09-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTDJ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamInternacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('club', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('talle', models.IntegerField()),
                ('colores', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CamNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('club', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('talle', models.IntegerField()),
                ('colores', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CamSeleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('pais', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('talle', models.IntegerField()),
                ('colores', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Accesorio',
        ),
        migrations.DeleteModel(
            name='Bicicleta',
        ),
        migrations.DeleteModel(
            name='Indumentaria',
        ),
    ]
