# Generated by Django 4.2.5 on 2023-09-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTDJ', '0002_caminternacional_camnacional_camseleccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caminternacional',
            name='talle',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='camnacional',
            name='talle',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='camseleccion',
            name='talle',
            field=models.CharField(max_length=10),
        ),
    ]
